# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZReader.ui'
#
# Created: Sat Jul 23 19:20:03 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ZReader(object):
    def setupUi(self, ZReader):
        ZReader.setObjectName(_fromUtf8("ZReader"))
        ZReader.resize(754, 565)
        self.centralwidget = QtGui.QWidget(ZReader)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.feedList = QtGui.QListWidget(self.layoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.feedList.setPalette(palette)
        self.feedList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.feedList.setObjectName(_fromUtf8("feedList"))
        self.verticalLayout.addWidget(self.feedList)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty(_fromUtf8("value"), -1)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidget = QtGui.QTableWidget(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 222, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tableWidget.setPalette(palette)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.textEdit = QtGui.QTextEdit(self.splitter)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_3.addWidget(self.splitter_2)
        ZReader.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ZReader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        ZReader.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ZReader)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ZReader.setStatusBar(self.statusbar)
        self.actionLogin_Google_Account = QtGui.QAction(ZReader)
        self.actionLogin_Google_Account.setObjectName(_fromUtf8("actionLogin_Google_Account"))
        self.actionLogout_Google_Account = QtGui.QAction(ZReader)
        self.actionLogout_Google_Account.setObjectName(_fromUtf8("actionLogout_Google_Account"))
        self.actionRegister_New_Account = QtGui.QAction(ZReader)
        self.actionRegister_New_Account.setObjectName(_fromUtf8("actionRegister_New_Account"))
        self.menu.addAction(self.actionLogin_Google_Account)
        self.menu.addAction(self.actionLogout_Google_Account)
        self.menu.addAction(self.actionRegister_New_Account)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(ZReader)
        QtCore.QMetaObject.connectSlotsByName(ZReader)

    def retranslateUi(self, ZReader):
        ZReader.setWindowTitle(QtGui.QApplication.translate("ZReader", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ZReader", "查看", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("ZReader", "所有", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("ZReader", "已读", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("ZReader", "加星的条目", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("ZReader", "分享的条目", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("ZReader", "账户", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogin_Google_Account.setText(QtGui.QApplication.translate("ZReader", "Log&in Google Account", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogout_Google_Account.setText(QtGui.QApplication.translate("ZReader", "Log&out Google Account", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegister_New_Account.setText(QtGui.QApplication.translate("ZReader", "&Register New Account", None, QtGui.QApplication.UnicodeUTF8))

