# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZReader.ui'
#
# Created: Sun Jul 17 21:44:19 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ZReader(object):
    def setupUi(self, ZReader):
        ZReader.setObjectName(_fromUtf8("ZReader"))
        ZReader.resize(800, 600)
        self.centralwidget = QtGui.QWidget(ZReader)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.ReadingTable = QtGui.QTableWidget(self.tab)
        self.ReadingTable.setAlternatingRowColors(False)
        self.ReadingTable.setGridStyle(QtCore.Qt.DashLine)
        self.ReadingTable.setRowCount(20)
        self.ReadingTable.setColumnCount(3)
        self.ReadingTable.setObjectName(_fromUtf8("ReadingTable"))
        self.ReadingTable.setColumnCount(3)
        self.ReadingTable.setRowCount(20)
        self.ReadingTable.horizontalHeader().setVisible(False)
        self.ReadingTable.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.ReadingTable)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.StarredTable = QtGui.QTableWidget(self.tab_2)
        self.StarredTable.setAlternatingRowColors(False)
        self.StarredTable.setGridStyle(QtCore.Qt.DashLine)
        self.StarredTable.setRowCount(20)
        self.StarredTable.setColumnCount(3)
        self.StarredTable.setObjectName(_fromUtf8("StarredTable"))
        self.StarredTable.setColumnCount(3)
        self.StarredTable.setRowCount(20)
        self.StarredTable.horizontalHeader().setVisible(False)
        self.StarredTable.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.StarredTable)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.SharedTable = QtGui.QTableWidget(self.tab_3)
        self.SharedTable.setAlternatingRowColors(False)
        self.SharedTable.setGridStyle(QtCore.Qt.DashLine)
        self.SharedTable.setRowCount(20)
        self.SharedTable.setColumnCount(3)
        self.SharedTable.setObjectName(_fromUtf8("SharedTable"))
        self.SharedTable.setColumnCount(3)
        self.SharedTable.setRowCount(20)
        self.SharedTable.horizontalHeader().setVisible(False)
        self.SharedTable.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.SharedTable)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.textEdit = QtGui.QTextEdit(self.splitter)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_2.addWidget(self.splitter)
        ZReader.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ZReader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        ZReader.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ZReader)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ZReader.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(ZReader)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.feedList = QtGui.QListWidget(self.dockWidgetContents)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.feedList.setPalette(palette)
        self.feedList.setObjectName(_fromUtf8("feedList"))
        self.verticalLayout.addWidget(self.feedList)
        self.progressBar = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty(_fromUtf8("value"), -1)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.dockWidget.setWidget(self.dockWidgetContents)
        ZReader.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionLogin_Google_Account = QtGui.QAction(ZReader)
        self.actionLogin_Google_Account.setObjectName(_fromUtf8("actionLogin_Google_Account"))
        self.actionLogout_Google_Account = QtGui.QAction(ZReader)
        self.actionLogout_Google_Account.setObjectName(_fromUtf8("actionLogout_Google_Account"))
        self.actionRegister_New_Account = QtGui.QAction(ZReader)
        self.actionRegister_New_Account.setObjectName(_fromUtf8("actionRegister_New_Account"))
        self.menu.addAction(self.actionLogin_Google_Account)
        self.menu.addAction(self.actionLogout_Google_Account)
        self.menu.addAction(self.actionRegister_New_Account)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(ZReader)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ZReader)

    def retranslateUi(self, ZReader):
        ZReader.setWindowTitle(QtGui.QApplication.translate("ZReader", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ZReader", "Reading Items", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ZReader", "Starred Items", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ZReader", "Shared Items", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("ZReader", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("ZReader", "Feed List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogin_Google_Account.setText(QtGui.QApplication.translate("ZReader", "Log&in Google Account", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogout_Google_Account.setText(QtGui.QApplication.translate("ZReader", "Log&out Google Account", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegister_New_Account.setText(QtGui.QApplication.translate("ZReader", "&Register New Account", None, QtGui.QApplication.UnicodeUTF8))

